apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deployersets.core.hybridapp.io
spec:
  group: core.hybridapp.io
  names:
    kind: DeployerSet
    listKind: DeployerSetList
    plural: deployersets
    singular: deployerset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: DeployerSet is the Schema for the deployersets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DeployerSetSpec defines the desired state of DeployerSet
          type: object
        status:
          description: DeployerSetStatus defines the observed state of DeployerSet
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
