kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ham-resource-discoverer
  labels:
    app.kubernetes.io/instance: ham-resource-discoverer
    app.kubernetes.io/managed-by: ham-resource-discoverer
    app.kubernetes.io/name: hybridApplication
subjects:
  - kind: ServiceAccount
    name: ham-resource-discoverer
    namespace: default
roleRef:
  kind: ClusterRole
  name: ham-resource-discoverer
  apiGroup: rbac.authorization.k8s.io
