apiVersion: v1
kind: ServiceAccount
metadata:
  name: ham-resource-discoverer
  labels:
    app.kubernetes.io/instance: ham-resource-discoverer
    app.kubernetes.io/managed-by: ham-resource-discoverer
    app.kubernetes.io/name: hybridApplication
