apiVersion: core.hybridapp.io/v1alpha1
kind: Deployer
metadata:
  name: cloudforms
  labels:
    deployer-type: cloudforms
  annotations:
    "core.hybridapp.io/deployer-in-cluster": "true"
spec:
  type: cloudforms
